import { NgModule } from "@angular/core";
import {
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatCardModule,
  MatDividerModule,
  MatIconModule,
  MatMenuModule,
  MatSidenavModule,
  MatToolbarModule,
  MatListModule,
  MatTooltipModule,
  MatBadgeModule,
  MatGridListModule,
  MatTabsModule,
  MatCheckboxModule,
  MatDialogModule,
  MatAutocompleteModule,
  MatChipsModule,
  MatButtonToggleModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatRadioModule,
  MatSnackBarModule
} from "@angular/material";
import { LayoutModule } from "@angular/cdk/layout";
import { TextFieldModule } from "@angular/cdk/text-field";

@NgModule({
  declarations: [],
  imports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatDividerModule,
    MatIconModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTooltipModule,
    MatBadgeModule,
    LayoutModule,
    MatGridListModule,
    MatTabsModule,
    MatCheckboxModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    TextFieldModule,
    MatRadioModule,
    MatSnackBarModule
  ],
  exports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatDividerModule,
    MatIconModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTooltipModule,
    MatBadgeModule,
    LayoutModule,
    MatGridListModule,
    MatTabsModule,
    MatCheckboxModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    TextFieldModule,
    MatRadioModule,
    MatSnackBarModule
  ]
})
export class AngularMaterialModule {}
